### ISSUE TITLE
improper token hash been passed even though i put valid tokens

### ISSUE THREAD

**Issue by xw8-568** [okuru-xyz/indigo-selfbot#25]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B6418A0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B6418D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B641900>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B641930>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B641960>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B641990>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FB6B6417E0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001FB6B44D060>, 2984.687)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001FB6B641A20>
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Client.start() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 300, in static_login  
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 254, in request       
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 665, in start       
    await self.login(*args, bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 511, in login       
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 304, in static_login  
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by Shkeffy** [comment]
You have to use a user token, not a bot token. Make sure that is the right token being used.

**Comment by Francesco2426** [comment]
the nuker supports selfbots too yknow

**Comment by Shkeffy** [comment]
Yeah, and he must have done the wrong one.

**Comment by Gowixx** [comment]
Closing as it is user usage issue.
